### ISSUE TITLE
Очистка всех сессий пользователя

### ISSUE THREAD

**Issue by belochka98** [dlabs71/spring-authorization-server-example#8]
https://github.com/dlabs71/spring-authorization-server-example/blob/815e3f8bdb56d449fcba32aaae3ab748fd027eaf/j-sso/src/main/java/ru/dlabs/sas/example/jsso/service/impl/DefaultAccountService.java#L102

В данном блоке очищается (logout) только конкретная сессия пользователя - текущая, пользователь, в свою очередь, может залогиниться с нескольких устройств/браузеров, возможно следует подумать над FindByIndexNameSessionRepository.deleteById для очистки всех сессий пользователя при удалении аккаунта

**Comment by dlabs71** [comment]
Согласен. Удалять все его активные сессии при удалении акаута нужно.
Добавил в метод DefaultAccountService.deleteCurrentUser() очистку сессий пользователя.
